services:
  - type: web
    name: s-hospital
    runtime: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_NAME
        value: SHospital
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false   # Lo pondrás manualmente con la URL de Render
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false   # URL del host de tu base de datos
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
