services:
  - type: web
    name: s-hospital
    runtime: php
    buildCommand: "./render-build.sh"
    startCommand: "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_NAME
        value: SHospital
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false   # Lo pondrás manualmente con la URL de Render
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d7sovdsm0tmc73dctoi0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: hospital_db_8dhb
      - key: DB_USERNAME
        value: hospital_db_8dhb_user
      - key: DB_PASSWORD
        value: V27VMTXR8tRYPrzzh8IiDrnRReOvS5hs
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
